apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-conversao-temperatura
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-conversao-temperatura
  template:
    metadata:
      labels:
        app: app-conversao-temperatura
    spec:
      containers:
      - name: app-conversao-temperatura
        image: carcheno/conversao-temperatura:v1
---
apiVersion: v1
kind: Service
metadata:
  name: srv-conversao-temperatura
spec:
  selector:
    app: app-conversao-temperatura
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: NodePort